### ISSUE TITLE
Infinite Update Loop Warning when Adding Newline Break

### ISSUE THREAD

**Issue by NWRichmond** [paramander/contentful-rich-text-vue-renderer#33] opened 2021-07-10 00:51 UTC
## The Problem

According to #29, the recommended way to add `<br />`s to a content node is to use custom `node-renderers` [as demonstrated `/src/index.test.js`](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/6b21fcf23ba6904235c70d389f315df0bfe13c5c/src/index.test.js#L403-L426).

However when using those `node-renderers`, Vue warns of an infinite update loop:

> You may have an infinite update loop in a component render function.

When tested in a Nuxt app, I see the same warning when the dev server is running. When statically generating a page that uses this render function, the app gets stuck in a loop during hydration, and the page fails to load.

## Minimal Reproduction

I created a [Code Sandbox](https://codesandbox.io/s/vigilant-satoshi-w4hhc?file=/src/App.vue) based on [`/src/index.test.js`](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/6b21fcf23ba6904235c70d389f315df0bfe13c5c/src/index.test.js#L403-L426) - notice the warning:

<img width="600" alt="vue-console-warn" src="https://user-images.githubusercontent.com/5732000/125147839-eba7fc00-e0fb-11eb-8856-fda8efe26b4f.png">

## Discussion

It seems like something [here](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/6b21fcf23ba6904235c70d389f315df0bfe13c5c/src/index.test.js#L407-L424) needs to change, but I'm not sure what. I'll keep experimenting, but would appreciate any and all help with this. Please feel free to fork [the Code Sandbox](https://codesandbox.io/s/vigilant-satoshi-w4hhc?file=/src/App.vue) to experiment.

**Comment by NWRichmond** [comment] 2021-07-10 01:15
Closing this after realizing that there's a workaround.

For reasons that aren't clear to me yet, when the `document` existed as Vue `data`, there was an update loop when passed to the `node-renderers`. Returning the `document` from a `method` sorted it out ([example](https://codesandbox.io/s/bold-proskuriakova-1d8wd)).

**Comment by NWRichmond** [comment] 2021-07-10 01:50
Reopening, since in many real-world cases the `document` will exist as `data`, as demonstrated in [the README](https://github.com/paramander/contentful-rich-text-vue-renderer/blob/master/README.md).

**Comment by tolgap** [comment] 2021-07-19 14:53
@NWRichmond I figured out what the issue is. In my test example it reassigns `node.content`, which triggers the component to rerender _while_ rendering the text node. This can be avoided by doing the following:

```
        [BLOCKS.PARAGRAPH]: (node, key, h, next) => {
          const nodeContentWithNewlineBr = node.content.map(childNode => {
            if (childNode.nodeType === 'text') {
              const splittedValue = childNode.value.split("\n");
              return splittedValue.reduce((aggregate, v, i) => (
                [
                  ...aggregate,
                  { ...childNode, value: v },
                  { nodeType: 'break', key: `${key}-br-${i}` }
                ]
              ), []).slice(0, -1);
            }

            return childNode;
          });

          const content = [].concat.apply([], nodeContentWithNewlineBr);

          return h('p', { key }, next(content, key, h, next));
        }
```

So we avoid reassigning `node.content`. See https://codesandbox.io/s/dreamy-bassi-0whgo?file=/src/App.vue

If you want to fix this in the tests and open a PR, I would be very grateful!

**Comment by NWRichmond** [comment] 2021-07-19 17:33
Thank you so much, @tolgap! I've opened #34 to make those adjustments to the tests.

**Closed as completed** 2021-07-19 17:37 UTC
